name: Release MMKV XCFramework

on:
  push:
    branches: [ "main" ]
    tags:
      - 'mmkv-v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for MMKV to release (e.g., 1.3.14)'
        required: true
        type: string

jobs:
  build:
    name: Build MMKV from Pods to xcframework
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check tools
        run: |
          pod --version
          xcodebuild -version

      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            VERSION=${GITHUB_REF#refs/tags/mmkv-v}
          else
            VERSION=${{ github.event.inputs.version }}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Podfile
        run: |
          cat > Podfile << EOF
          platform :ios, '16.0'
          use_frameworks!

          target 'MMKVXC' do
            pod 'MMKV', '${{ steps.get_version.outputs.version }}'
          end
          EOF

          echo "Generated Podfile:"
          cat Podfile
