name: Release MMKV XCFramework

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for MMKV to release (e.g., 1.3.14)'
        required: true
        type: string

jobs:
  build:
    name: Build MMKV from Pods to xcframework
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check tools
        run: |
          pod --version
          xcodebuild -version
